# Generated by Django 2.1.5 on 2019-01-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=264)),
                ('event_from_date', models.DateField()),
                ('event_to_date', models.DateField()),
            ],
        ),
    ]
