# Generated by Django 2.1.5 on 2019-02-01 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('field_type', models.CharField(max_length=10)),
                ('field_label', models.CharField(max_length=50)),
                ('is_mandatory', models.BooleanField()),
                ('show_in_search', models.BooleanField()),
                ('include_in_search', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.Event')),
            ],
        ),
    ]
