# Generated by Django 2.1.5 on 2019-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_eventfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfield',
            name='column_in_excel',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='font_family',
            field=models.CharField(default='Calibri', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='font_size',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='font_style',
            field=models.CharField(default='normal', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='font_weight',
            field=models.CharField(default='normal', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='left',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='show_in_print',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='show_in_register',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='text_align',
            field=models.CharField(default='left', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='top',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfield',
            name='width',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
