# Generated by Django 2.1.5 on 2019-02-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_badgecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBadgeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_catagory_code', models.CharField(max_length=50)),
                ('badge_category_desc', models.CharField(max_length=50)),
                ('show_in_register', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.Event')),
            ],
        ),
    ]
