# Generated by Django 2.1.5 on 2019-02-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_eventbadgecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfield',
            name='font_family',
            field=models.CharField(default='Calibri', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventfield',
            name='font_size',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='eventfield',
            name='font_style',
            field=models.CharField(default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventfield',
            name='font_weight',
            field=models.CharField(default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventfield',
            name='text_align',
            field=models.CharField(default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventfield',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
