# Generated by Django 2.1.5 on 2019-02-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_auto_20190208_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbadgecategory',
            old_name='badge_catagory_code',
            new_name='badge_category_code',
        ),
    ]
