# Generated by Django 2.1.5 on 2019-03-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_auto_20190208_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='setup_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
