# Generated by Django 2.1.5 on 2019-03-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_event_event_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_logo',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
    ]
