# Generated by Django 2.1.5 on 2019-03-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_eventdata_importdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importdata',
            name='event',
        ),
    ]
